/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-07-24 10:15:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Model.Customer;

public final class customer_002dindex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Model.Customer");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"description\" content=\"Male_Fashion Template\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"Male_Fashion, unica, creative, html\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>Male-Fashion | Template</title>\r\n");
      out.write("    <script>\r\n");
      out.write("        addEventListener(\"load\", function() {\r\n");
      out.write("            setTimeout(hideURLbar, 0);\r\n");
      out.write("        }, false);\r\n");
      out.write("\r\n");
      out.write("        function hideURLbar() {\r\n");
      out.write("            window.scrollTo(0, 1);\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Font -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap\"\r\n");
      out.write("    rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Css Styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/elegant-icons.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/magnific-popup.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/nice-select.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/slicknav.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");

Customer u = null;
if(session.getAttribute("data")!=null){
	u = (Customer)session.getAttribute("data");
}
else{
	response.sendRedirect("customer-login.jsp");
}

      out.write("\r\n");
      out.write("    <!-- Page Preloder -->\r\n");
      out.write("    <div id=\"preloder\">\r\n");
      out.write("        <div class=\"loader\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Offcanvas Menu Begin -->\r\n");
      out.write("    <div class=\"offcanvas-menu-overlay\"></div>\r\n");
      out.write("    <div class=\"offcanvas-menu-wrapper\">\r\n");
      out.write("        <div class=\"offcanvas__option\">\r\n");
      out.write("            <div class=\"offcanvas__links\">\r\n");
      out.write("                <a href=\"#\">Sign in</a>\r\n");
      out.write("                <a href=\"#\">FAQs</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"offcanvas__top__hover\">\r\n");
      out.write("                <span>Usd <i class=\"arrow_carrot-down\"></i></span>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>USD</li>\r\n");
      out.write("                    <li>EUR</li>\r\n");
      out.write("                    <li>USD</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"offcanvas__nav__option\">\r\n");
      out.write("            <a href=\"#\" class=\"search-switch\"><img src=\"img/icon/search.png\" alt=\"\"></a>\r\n");
      out.write("            <a href=\"#\"><img src=\"img/icon/heart.png\" alt=\"\"></a>\r\n");
      out.write("            <a href=\"#\"><img src=\"img/icon/cart.png\" alt=\"\"> <span>0</span></a>\r\n");
      out.write("            <div class=\"price\">$0.00</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"mobile-menu-wrap\"></div>\r\n");
      out.write("        <div class=\"offcanvas__text\">\r\n");
      out.write("            <p>Free shipping, 30-day return or refund guarantee.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Offcanvas Menu End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Header Section Begin -->\r\n");
      out.write("    <header class=\"header\">\r\n");
      out.write("        <div class=\"header__top\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-6 col-md-7\">\r\n");
      out.write("                        <div class=\"header__top__left\">\r\n");
      out.write("                            <p>Free shipping, 30-day return or refund guarantee.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6 col-md-5\">\r\n");
      out.write("                        <div class=\"header__top__right\">\r\n");
      out.write("                            <div class=\"header__top__links\">\r\n");
      out.write("                                <a href=\"#\">Sign in</a>\r\n");
      out.write("                                <a href=\"#\">FAQs</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"header__top__hover\">\r\n");
      out.write("                                <span>Usd <i class=\"arrow_carrot-down\"></i></span>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li>USD</li>\r\n");
      out.write("                                    <li>EUR</li>\r\n");
      out.write("                                    <li>USD</li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-3 col-md-3\">\r\n");
      out.write("                    <div class=\"header__logo\">\r\n");
      out.write("                        <a href=\"./index.html\"><img src=\"img/logo.png\" alt=\"\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 col-md-6\">\r\n");
      out.write("                    <nav class=\"header__menu mobile-menu\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li class=\"active\"><a href=\"./index.html\">Home</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Pages</a>\r\n");
      out.write("                                <ul class=\"dropdown\">\r\n");
      out.write("                                    <li><a href=\"./about.html\">About Us</a></li>\r\n");
      out.write("                                    <li><a href=\"./shop-details.html\">Shop Details</a></li>\r\n");
      out.write("                                    <li><a href=\"./shopping-cart.html\">Shopping Cart</a></li>\r\n");
      out.write("                                    <li><a href=\"./checkout.html\">Check Out</a></li>\r\n");
      out.write("                                    <li><a href=\"./blog-details.html\">Blog Details</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"#\">");
      out.print(u.getName());
      out.write("</a>\r\n");
      out.write("                            <ul class=\"dropdown\">\r\n");
      out.write("                                    <li><a href=\"customer-profile.jsp\">Profile</a></li>\r\n");
      out.write("                                    <li><a href=\"customer-change-password.jsp\">Change Password</a></li>\r\n");
      out.write("                                    <li><a href=\"customer-logout.jsp\">Logout</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"./contact.html\">Contacts</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-3\">\r\n");
      out.write("                    <div class=\"header__nav__option\">\r\n");
      out.write("                        <a href=\"#\" class=\"search-switch\"><img src=\"img/icon/search.png\" alt=\"\"></a>\r\n");
      out.write("                        <a href=\"#\"><img src=\"img/icon/heart.png\" alt=\"\"></a>\r\n");
      out.write("                        <a href=\"#\"><img src=\"img/icon/cart.png\" alt=\"\"> <span>0</span></a>\r\n");
      out.write("                        <div class=\"price\">$0.00</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"canvas__open\"><i class=\"fa fa-bars\"></i></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- Header Section End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Hero Section Begin -->\r\n");
      out.write("    <section class=\"hero\">\r\n");
      out.write("        <div class=\"hero__slider owl-carousel\">\r\n");
      out.write("            <div class=\"hero__items set-bg\" data-setbg=\"img/hero/hero-1.jpg\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-xl-5 col-lg-7 col-md-8\">\r\n");
      out.write("                            <div class=\"hero__text\">\r\n");
      out.write("                                <h6>Summer Collection</h6>\r\n");
      out.write("                                <h2>Fall - Winter Collections 2030</h2>\r\n");
      out.write("                                <p>A specialist label creating luxury essentials. Ethically crafted with an unwavering\r\n");
      out.write("                                commitment to exceptional quality.</p>\r\n");
      out.write("                                <a href=\"#\" class=\"primary-btn\">Shop now <span class=\"arrow_right\"></span></a>\r\n");
      out.write("                                <div class=\"hero__social\">\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-pinterest\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-instagram\"></i></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"hero__items set-bg\" data-setbg=\"img/hero/hero-2.jpg\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-xl-5 col-lg-7 col-md-8\">\r\n");
      out.write("                            <div class=\"hero__text\">\r\n");
      out.write("                                <h6>Summer Collection</h6>\r\n");
      out.write("                                <h2>Fall - Winter Collections 2030</h2>\r\n");
      out.write("                                <p>A specialist label creating luxury essentials. Ethically crafted with an unwavering\r\n");
      out.write("                                commitment to exceptional quality.</p>\r\n");
      out.write("                                <a href=\"#\" class=\"primary-btn\">Shop now <span class=\"arrow_right\"></span></a>\r\n");
      out.write("                                <div class=\"hero__social\">\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-pinterest\"></i></a>\r\n");
      out.write("                                    <a href=\"#\"><i class=\"fa fa-instagram\"></i></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Hero Section End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Banner Section Begin -->\r\n");
      out.write("    <section class=\"banner spad\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-7 offset-lg-4\">\r\n");
      out.write("                    <div class=\"banner__item\">\r\n");
      out.write("                        <div class=\"banner__item__pic\">\r\n");
      out.write("                            <img src=\"img/banner/banner-1.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"banner__item__text\">\r\n");
      out.write("                            <h2>Clothing Collections 2030</h2>\r\n");
      out.write("                            <a href=\"#\">Shop now</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-5\">\r\n");
      out.write("                    <div class=\"banner__item banner__item--middle\">\r\n");
      out.write("                        <div class=\"banner__item__pic\">\r\n");
      out.write("                            <img src=\"img/banner/banner-2.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"banner__item__text\">\r\n");
      out.write("                            <h2>Accessories</h2>\r\n");
      out.write("                            <a href=\"#\">Shop now</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-7\">\r\n");
      out.write("                    <div class=\"banner__item banner__item--last\">\r\n");
      out.write("                        <div class=\"banner__item__pic\">\r\n");
      out.write("                            <img src=\"img/banner/banner-3.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"banner__item__text\">\r\n");
      out.write("                            <h2>Shoes Spring 2030</h2>\r\n");
      out.write("                            <a href=\"#\">Shop now</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Banner Section End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Product Section Begin -->\r\n");
      out.write("    <section class=\"product spad\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <ul class=\"filter__controls\">\r\n");
      out.write("                        <li class=\"active\" data-filter=\"*\">Best Sellers</li>\r\n");
      out.write("                        <li data-filter=\".new-arrivals\">New Arrivals</li>\r\n");
      out.write("                        <li data-filter=\".hot-sales\">Hot Sales</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row product__filter\">\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 col-sm-6 col-md-6 col-sm-6 mix new-arrivals\">\r\n");
      out.write("                    <div class=\"product__item\">\r\n");
      out.write("                        <div class=\"product__item__pic set-bg\" data-setbg=\"img/product/product-1.jpg\">\r\n");
      out.write("                            <span class=\"label\">New</span>\r\n");
      out.write("                            <ul class=\"product__hover\">\r\n");
      out.write("                                <li><a href=\"#\"><img src=\"img/icon/heart.png\" alt=\"\"></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><img src=\"img/icon/compare.png\" alt=\"\"> <span>Compare</span></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><img src=\"img/icon/search.png\" alt=\"\"></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"product__item__text\">\r\n");
      out.write("                            <h6>Piqué Biker Jacket</h6>\r\n");
      out.write("                            <a href=\"#\" class=\"add-cart\">+ Add To Cart</a>\r\n");
      out.write("                            <div class=\"rating\">\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h5>$67.24</h5>\r\n");
      out.write("                            <div class=\"product__color__select\">\r\n");
      out.write("                                <label for=\"pc-1\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"pc-1\">\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label class=\"active black\" for=\"pc-2\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"pc-2\">\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label class=\"grey\" for=\"pc-3\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"pc-3\">\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 col-sm-6 col-md-6 col-sm-6 mix hot-sales\">\r\n");
      out.write("                    <div class=\"product__item\">\r\n");
      out.write("                        <div class=\"product__item__pic set-bg\" data-setbg=\"img/product/product-2.jpg\">\r\n");
      out.write("                            <ul class=\"product__hover\">\r\n");
      out.write("                                <li><a href=\"#\"><img src=\"img/icon/heart.png\" alt=\"\"></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><img src=\"img/icon/compare.png\" alt=\"\"> <span>Compare</span></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><img src=\"img/icon/search.png\" alt=\"\"></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"product__item__text\">\r\n");
      out.write("                            <h6>Piqué Biker Jacket</h6>\r\n");
      out.write("                            <a href=\"#\" class=\"add-cart\">+ Add To Cart</a>\r\n");
      out.write("                            <div class=\"rating\">\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h5>$67.24</h5>\r\n");
      out.write("                            <div class=\"product__color__select\">\r\n");
      out.write("                                <label for=\"pc-4\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"pc-4\">\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label class=\"active black\" for=\"pc-5\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"pc-5\">\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label class=\"grey\" for=\"pc-6\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"pc-6\">\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 col-sm-6 col-md-6 col-sm-6 mix new-arrivals\">\r\n");
      out.write("                    <div class=\"product__item sale\">\r\n");
      out.write("                        <div class=\"product__item__pic set-bg\" data-setbg=\"img/product/product-3.jpg\">\r\n");
      out.write("                            <span class=\"label\">Sale</span>\r\n");
      out.write("                            <ul class=\"product__hover\">\r\n");
      out.write("                                <li><a href=\"#\"><img src=\"img/icon/heart.png\" alt=\"\"></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><img src=\"img/icon/compare.png\" alt=\"\"> <span>Compare</span></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><img src=\"img/icon/search.png\" alt=\"\"></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"product__item__text\">\r\n");
      out.write("                            <h6>Multi-pocket Chest Bag</h6>\r\n");
      out.write("                            <a href=\"#\" class=\"add-cart\">+ Add To Cart</a>\r\n");
      out.write("                            <div class=\"rating\">\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h5>$43.48</h5>\r\n");
      out.write("                            <div class=\"product__color__select\">\r\n");
      out.write("                                <label for=\"pc-7\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"pc-7\">\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label class=\"active black\" for=\"pc-8\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"pc-8\">\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label class=\"grey\" for=\"pc-9\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"pc-9\">\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 col-sm-6 col-md-6 col-sm-6 mix hot-sales\">\r\n");
      out.write("                    <div class=\"product__item\">\r\n");
      out.write("                        <div class=\"product__item__pic set-bg\" data-setbg=\"img/product/product-4.jpg\">\r\n");
      out.write("                            <ul class=\"product__hover\">\r\n");
      out.write("                                <li><a href=\"#\"><img src=\"img/icon/heart.png\" alt=\"\"></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><img src=\"img/icon/compare.png\" alt=\"\"> <span>Compare</span></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><img src=\"img/icon/search.png\" alt=\"\"></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"product__item__text\">\r\n");
      out.write("                            <h6>Diagonal Textured Cap</h6>\r\n");
      out.write("                            <a href=\"#\" class=\"add-cart\">+ Add To Cart</a>\r\n");
      out.write("                            <div class=\"rating\">\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h5>$60.9</h5>\r\n");
      out.write("                            <div class=\"product__color__select\">\r\n");
      out.write("                                <label for=\"pc-10\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"pc-10\">\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label class=\"active black\" for=\"pc-11\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"pc-11\">\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label class=\"grey\" for=\"pc-12\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"pc-12\">\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 col-sm-6 col-md-6 col-sm-6 mix new-arrivals\">\r\n");
      out.write("                    <div class=\"product__item\">\r\n");
      out.write("                        <div class=\"product__item__pic set-bg\" data-setbg=\"img/product/product-5.jpg\">\r\n");
      out.write("                            <ul class=\"product__hover\">\r\n");
      out.write("                                <li><a href=\"#\"><img src=\"img/icon/heart.png\" alt=\"\"></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><img src=\"img/icon/compare.png\" alt=\"\"> <span>Compare</span></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><img src=\"img/icon/search.png\" alt=\"\"></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"product__item__text\">\r\n");
      out.write("                            <h6>Lether Backpack</h6>\r\n");
      out.write("                            <a href=\"#\" class=\"add-cart\">+ Add To Cart</a>\r\n");
      out.write("                            <div class=\"rating\">\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h5>$31.37</h5>\r\n");
      out.write("                            <div class=\"product__color__select\">\r\n");
      out.write("                                <label for=\"pc-13\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"pc-13\">\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label class=\"active black\" for=\"pc-14\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"pc-14\">\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label class=\"grey\" for=\"pc-15\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"pc-15\">\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 col-sm-6 col-md-6 col-sm-6 mix hot-sales\">\r\n");
      out.write("                    <div class=\"product__item sale\">\r\n");
      out.write("                        <div class=\"product__item__pic set-bg\" data-setbg=\"img/product/product-6.jpg\">\r\n");
      out.write("                            <span class=\"label\">Sale</span>\r\n");
      out.write("                            <ul class=\"product__hover\">\r\n");
      out.write("                                <li><a href=\"#\"><img src=\"img/icon/heart.png\" alt=\"\"></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><img src=\"img/icon/compare.png\" alt=\"\"> <span>Compare</span></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><img src=\"img/icon/search.png\" alt=\"\"></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"product__item__text\">\r\n");
      out.write("                            <h6>Ankle Boots</h6>\r\n");
      out.write("                            <a href=\"#\" class=\"add-cart\">+ Add To Cart</a>\r\n");
      out.write("                            <div class=\"rating\">\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h5>$98.49</h5>\r\n");
      out.write("                            <div class=\"product__color__select\">\r\n");
      out.write("                                <label for=\"pc-16\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"pc-16\">\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label class=\"active black\" for=\"pc-17\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"pc-17\">\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label class=\"grey\" for=\"pc-18\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"pc-18\">\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 col-sm-6 col-md-6 col-sm-6 mix new-arrivals\">\r\n");
      out.write("                    <div class=\"product__item\">\r\n");
      out.write("                        <div class=\"product__item__pic set-bg\" data-setbg=\"img/product/product-7.jpg\">\r\n");
      out.write("                            <ul class=\"product__hover\">\r\n");
      out.write("                                <li><a href=\"#\"><img src=\"img/icon/heart.png\" alt=\"\"></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><img src=\"img/icon/compare.png\" alt=\"\"> <span>Compare</span></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><img src=\"img/icon/search.png\" alt=\"\"></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"product__item__text\">\r\n");
      out.write("                            <h6>T-shirt Contrast Pocket</h6>\r\n");
      out.write("                            <a href=\"#\" class=\"add-cart\">+ Add To Cart</a>\r\n");
      out.write("                            <div class=\"rating\">\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h5>$49.66</h5>\r\n");
      out.write("                            <div class=\"product__color__select\">\r\n");
      out.write("                                <label for=\"pc-19\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"pc-19\">\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label class=\"active black\" for=\"pc-20\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"pc-20\">\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label class=\"grey\" for=\"pc-21\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"pc-21\">\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 col-sm-6 col-md-6 col-sm-6 mix hot-sales\">\r\n");
      out.write("                    <div class=\"product__item\">\r\n");
      out.write("                        <div class=\"product__item__pic set-bg\" data-setbg=\"img/product/product-8.jpg\">\r\n");
      out.write("                            <ul class=\"product__hover\">\r\n");
      out.write("                                <li><a href=\"#\"><img src=\"img/icon/heart.png\" alt=\"\"></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><img src=\"img/icon/compare.png\" alt=\"\"> <span>Compare</span></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><img src=\"img/icon/search.png\" alt=\"\"></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"product__item__text\">\r\n");
      out.write("                            <h6>Basic Flowing Scarf</h6>\r\n");
      out.write("                            <a href=\"#\" class=\"add-cart\">+ Add To Cart</a>\r\n");
      out.write("                            <div class=\"rating\">\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                                <i class=\"fa fa-star-o\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h5>$26.28</h5>\r\n");
      out.write("                            <div class=\"product__color__select\">\r\n");
      out.write("                                <label for=\"pc-22\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"pc-22\">\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label class=\"active black\" for=\"pc-23\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"pc-23\">\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <label class=\"grey\" for=\"pc-24\">\r\n");
      out.write("                                    <input type=\"radio\" id=\"pc-24\">\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Product Section End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Categories Section Begin -->\r\n");
      out.write("    <section class=\"categories spad\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-3\">\r\n");
      out.write("                    <div class=\"categories__text\">\r\n");
      out.write("                        <h2>Clothings Hot <br /> <span>Shoe Collection</span> <br /> Accessories</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4\">\r\n");
      out.write("                    <div class=\"categories__hot__deal\">\r\n");
      out.write("                        <img src=\"img/product-sale.png\" alt=\"\">\r\n");
      out.write("                        <div class=\"hot__deal__sticker\">\r\n");
      out.write("                            <span>Sale Of</span>\r\n");
      out.write("                            <h5>$29.99</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 offset-lg-1\">\r\n");
      out.write("                    <div class=\"categories__deal__countdown\">\r\n");
      out.write("                        <span>Deal Of The Week</span>\r\n");
      out.write("                        <h2>Multi-pocket Chest Bag Black</h2>\r\n");
      out.write("                        <div class=\"categories__deal__countdown__timer\" id=\"countdown\">\r\n");
      out.write("                            <div class=\"cd-item\">\r\n");
      out.write("                                <span>3</span>\r\n");
      out.write("                                <p>Days</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"cd-item\">\r\n");
      out.write("                                <span>1</span>\r\n");
      out.write("                                <p>Hours</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"cd-item\">\r\n");
      out.write("                                <span>50</span>\r\n");
      out.write("                                <p>Minutes</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"cd-item\">\r\n");
      out.write("                                <span>18</span>\r\n");
      out.write("                                <p>Seconds</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <a href=\"#\" class=\"primary-btn\">Shop now</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Categories Section End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Instagram Section Begin -->\r\n");
      out.write("    <section class=\"instagram spad\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-8\">\r\n");
      out.write("                    <div class=\"instagram__pic\">\r\n");
      out.write("                        <div class=\"instagram__pic__item set-bg\" data-setbg=\"img/instagram/instagram-1.jpg\"></div>\r\n");
      out.write("                        <div class=\"instagram__pic__item set-bg\" data-setbg=\"img/instagram/instagram-2.jpg\"></div>\r\n");
      out.write("                        <div class=\"instagram__pic__item set-bg\" data-setbg=\"img/instagram/instagram-3.jpg\"></div>\r\n");
      out.write("                        <div class=\"instagram__pic__item set-bg\" data-setbg=\"img/instagram/instagram-4.jpg\"></div>\r\n");
      out.write("                        <div class=\"instagram__pic__item set-bg\" data-setbg=\"img/instagram/instagram-5.jpg\"></div>\r\n");
      out.write("                        <div class=\"instagram__pic__item set-bg\" data-setbg=\"img/instagram/instagram-6.jpg\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4\">\r\n");
      out.write("                    <div class=\"instagram__text\">\r\n");
      out.write("                        <h2>Instagram</h2>\r\n");
      out.write("                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut\r\n");
      out.write("                        labore et dolore magna aliqua.</p>\r\n");
      out.write("                        <h3>#Male_Fashion</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Instagram Section End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Latest Blog Section Begin -->\r\n");
      out.write("    <section class=\"latest spad\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"section-title\">\r\n");
      out.write("                        <span>Latest News</span>\r\n");
      out.write("                        <h2>Fashion New Trends</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6 col-sm-6\">\r\n");
      out.write("                    <div class=\"blog__item\">\r\n");
      out.write("                        <div class=\"blog__item__pic set-bg\" data-setbg=\"img/blog/blog-1.jpg\"></div>\r\n");
      out.write("                        <div class=\"blog__item__text\">\r\n");
      out.write("                            <span><img src=\"img/icon/calendar.png\" alt=\"\"> 16 February 2020</span>\r\n");
      out.write("                            <h5>What Curling Irons Are The Best Ones</h5>\r\n");
      out.write("                            <a href=\"#\">Read More</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6 col-sm-6\">\r\n");
      out.write("                    <div class=\"blog__item\">\r\n");
      out.write("                        <div class=\"blog__item__pic set-bg\" data-setbg=\"img/blog/blog-2.jpg\"></div>\r\n");
      out.write("                        <div class=\"blog__item__text\">\r\n");
      out.write("                            <span><img src=\"img/icon/calendar.png\" alt=\"\"> 21 February 2020</span>\r\n");
      out.write("                            <h5>Eternity Bands Do Last Forever</h5>\r\n");
      out.write("                            <a href=\"#\">Read More</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6 col-sm-6\">\r\n");
      out.write("                    <div class=\"blog__item\">\r\n");
      out.write("                        <div class=\"blog__item__pic set-bg\" data-setbg=\"img/blog/blog-3.jpg\"></div>\r\n");
      out.write("                        <div class=\"blog__item__text\">\r\n");
      out.write("                            <span><img src=\"img/icon/calendar.png\" alt=\"\"> 28 February 2020</span>\r\n");
      out.write("                            <h5>The Health Benefits Of Sunglasses</h5>\r\n");
      out.write("                            <a href=\"#\">Read More</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Latest Blog Section End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer Section Begin -->\r\n");
      out.write("    <footer class=\"footer\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("                    <div class=\"footer__about\">\r\n");
      out.write("                        <div class=\"footer__logo\">\r\n");
      out.write("                            <a href=\"#\"><img src=\"img/footer-logo.png\" alt=\"\"></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p>The customer is at the heart of our unique business model, which includes design.</p>\r\n");
      out.write("                        <a href=\"#\"><img src=\"img/payment.png\" alt=\"\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-2 offset-lg-1 col-md-3 col-sm-6\">\r\n");
      out.write("                    <div class=\"footer__widget\">\r\n");
      out.write("                        <h6>Shopping</h6>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">Clothing Store</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Trending Shoes</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Accessories</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Sale</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-2 col-md-3 col-sm-6\">\r\n");
      out.write("                    <div class=\"footer__widget\">\r\n");
      out.write("                        <h6>Shopping</h6>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">Contact Us</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Payment Methods</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Delivary</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Return & Exchanges</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 offset-lg-1 col-md-6 col-sm-6\">\r\n");
      out.write("                    <div class=\"footer__widget\">\r\n");
      out.write("                        <h6>NewLetter</h6>\r\n");
      out.write("                        <div class=\"footer__newslatter\">\r\n");
      out.write("                            <p>Be the first to know about new arrivals, look books, sales & promos!</p>\r\n");
      out.write("                            <form action=\"#\">\r\n");
      out.write("                                <input type=\"text\" placeholder=\"Your email\">\r\n");
      out.write("                                <button type=\"submit\"><span class=\"icon_mail_alt\"></span></button>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12 text-center\">\r\n");
      out.write("                    <div class=\"footer__copyright__text\">\r\n");
      out.write("                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("                        <p>Copyright ©\r\n");
      out.write("                            <script>\r\n");
      out.write("                                document.write(new Date().getFullYear());\r\n");
      out.write("                            </script>2020\r\n");
      out.write("                            All rights reserved | This template is made with <i class=\"fa fa-heart-o\"\r\n");
      out.write("                            aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- Footer Section End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Search Begin -->\r\n");
      out.write("    <div class=\"search-model\">\r\n");
      out.write("        <div class=\"h-100 d-flex align-items-center justify-content-center\">\r\n");
      out.write("            <div class=\"search-close-switch\">+</div>\r\n");
      out.write("            <form class=\"search-model-form\">\r\n");
      out.write("                <input type=\"text\" id=\"search-input\" placeholder=\"Search here.....\">\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Search End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Js Plugins -->\r\n");
      out.write("    <script src=\"js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.nicescroll.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.countdown.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.slicknav.js\"></script>\r\n");
      out.write("    <script src=\"js/mixitup.min.js\"></script>\r\n");
      out.write("    <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
